directories:
  output: pack
  buildResources: assets
files:
  - filter:
      - build/**/*
      - ./main.js
      - ./build/**
      - ./package.json
      - ./preload.js
extraMetadata:
  main: build/electron.js
productName: baiyiyanzhengyi
appId: com.baiyi.baiyiyanzhengyi
copyright: xxxx
nsis:
  oneClick: false
  allowElevation: true
  allowToChangeInstallationDirectory: true
  installerIcon: ./pack/icons/icon.jpeg
  uninstallerIcon: ./pack/icons/icon.jpeg
  installerHeaderIcon: ./pack/icons/icon.jpeg
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: baiyiyanzhengyi
  include: pack/script/installer.nsh
dmg:
  contents:
    - x: 410
      'y': 150
      type: link
      path: /Applications
    - x: 130
      'y': 150
      type: file
mac:
  icon: pack/icons/icon.jpeg
win:
  icon: pack/icons/icon.jpeg
  target:
    - target: nsis
      arch:
        - ia32
linux:
  icon: pack/icons/icon.jpeg
  target:
    - deb
extends: react-cra
electronVersion: 16.0.4
